kind: pipeline
name: backend
load: secret

steps:
  - name: install
    image: gradle:8.5-alpine
    commands:
      - cd backend
      - ./gradlew build
#  - name: test
#    image: java
#    commands:
#      - cd backend
#      - test
  - name: build docker image
    image: plugins/docker
    settings:
      context: ./backend
      dockerfile: ./backend/Dockerfile
      username:
        from_secret: registry-username
      password:
        from_secret: registry-password
      repo: registry.sliceofbits.com/iprwc-backend
      registry: registry.sliceofbits.com/
      tags: latest

---
kind: pipeline
name: frontend
load: secret
steps:
  - name: install
    image: node:18
    commands:
      - cd front-end
      - npm install
#  - name: test
#    image: node:18
#    commands:
#      - wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
#      - sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
#      - apt-get update && apt-get install -y google-chrome-stable
#      - cd front-end
#      - npm test
  - name: build angular
    image: node:18
    commands:
      - cd front-end
      - npm run build
  - name: build docker image
    image: plugins/docker
    settings:
      context: ./front-end
      dockerfile: ./front-end/Dockerfile
      username:
        from_secret: registry-username
      password:
        from_secret: registry-password
      repo: registry.sliceofbits.com/iprwc-frontend
      registry: registry.sliceofbits.com/
      tags: latest


---
kind: pipeline
name: after
load: secret

steps:
  - name: ssh
    image: appleboy/drone-ssh
    settings:
      host:
        - 188.166.107.220
      username:
        from_secret: ssh_username
      password:
        from_secret: ssh_password
      port: 22
      command_timeout: 2m
      script:
        - cd iprwc/
        - docker-compose pull && docker-compose up -d

depends_on:
  - backend
  - frontend
